baseURL = 'https://gokulsasidhar.github.io/'
languageCode = 'en-us'
title = 'Days Spent Here'
theme = 'hugo-bearblog'

[markup.goldmark.renderer]
unsafe = true

[params]
hideMadeWithLine = true
mainSections = ['']